version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Initializing environment
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain nextwork --domain-owner 890238960412 --query authorizationToken --output text`
  build:
    commands:
      - echo Build started on `date`
      - mvn -s nextwork-web-project/src/main/webapp/settings.xml package

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn -s nextwork-web-project/src/main/webapp/settings.xml package
artifacts:
  files:
    - target/nextwork-web-project.war
    - appspec.yml
    - scripts/**/*

  discard-paths: no
